apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      # caso deixe apenas essa porta, o targetPort sera na mesma porta
      nodePort: 30000
  selector:
    app: primeiro-pod
